site_name: ugo_r_doc
site_description: A R documentation website.
site_author: Ugo Spark
copyright: null
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
remote_name: ugo_r_doc
pages:
    - Home: 'index.md'
    - An Introduction to R: 'An Introduction to R.md'
    - Jupyter Notebook and the R Kernel: 'Jupyter Notebook and the R Kernel.md'
    - Le logiciel R, maitriser le langage, effectuer des analyses (bio)statistiques: 'Le logiciel R, maitriser le langage, effectuer des analyses (bio)statistiques.md'
    - Working with the RStudio IDE: 'Working_with_RStudio_IDE.md'
    - I/O snippets & Cleaning: 'IO_snippets___Cleaning.md'
    - Reading Data into R with readr: 'Reading_Data_into_R_with_readr.md'
    - Data Wrangling: 'Data_Wrangling.md'
    - Plot Snippets:
        - Code & Plot Chunk Options: 'Code___Plot_Chunk_Options.md'
        - Plot Snippets for Exploratory (and some Explanatory) Analyses: 'Plot_snippets_-_Basics.md'
        - Plot Snippets - ggplot2: 'Plot_snippets_-_ggplot2.md'
        - Plot Snippets - Colours: 'Plot_snippets_-_Colours.md'
    - Charts & Colors: 'Charts.md'
    - Intermediate R: 'Intermediate_R.md'
    - Intermediate R - apply Functions: 'Intermediate_R_-_apply_Functions.md'  
    - A Hands-on Introduction to Statistics with R:
        - Statistics with R, Course One, Introduction: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_One,_Introduction.md'
        - Statistics with R, Course Two, Student's t-test: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Two,_Student_s_T-test.md'
        - Statistics with R, Course Three, Analysis of Variance: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Three,_Analysis_of_Variance.md'
        - Statistics with R, Course Four, Repeated Measures ANOVA: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Four,_Repeated_Measures_Anova.md'
        - Statistics with R, Course Five, Correlation and Regression: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Five,_Correlation_and_Regression.md'
        - Statistics with R, Course Six, Multiple Regression: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Six,_Multiple_Regression.md'
        - Statistics with R, Course Seven, Moderation and Mediation: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Seven,_Moderation_and_Mediation.md'
    - Big Data Analysis with Revolution R Enterprise: 'Big_Data_Analysis_with_Revolution_R_Enterprise.md'

theme: readthedocs
# Other themes:
    # readthedocs
    # mkdocs

# Build PDF & ePub (only on Readthedocs)
#formats: 
#    - pdf

# Interlinks
# [link](to_other_page.md)
# [link](../relative/page.md)

markdown_extensions:
    - wikilinks # internal links with [[bracketed]]
    - smarty # additional characters
    - subscript
    - superscript
    - nl2br # need a new line to break
    - toc:
        title: CONTENT
        permalink: True
        baselevel: 3