site_name: ugo_r_doc
site_url: https://ugoproto.github.io/ugo_r_doc/
#repo_url: https://github.com/ugoproto/ugo_r_doc
site_description: A R documentation website.
site_author: Ugo Sparks
#site_favicon: favicon.ico
copyright: © Ugo Sparks
google_analytics: 
    - 'UA-93008985-1'
    - 'auto'
#remote_branch: master
#remote_name: ugo_r_doc

pages:
    - Home: 'index.md'
    - An Introduction to R: 'An Introduction to R.md'
    - Le logiciel R, maitriser le langage, effectuer des analyses (bio)statistiques: 'Le logiciel R, maitriser le langage, effectuer des analyses (bio)statistiques.md'
    - R Cheat Sheets: 'R_CS.md'
    - Intermediate R:
        - Intermediate R: 'Intermediate_R.md'
        - Intermediate R - The apply Family: 'Intermediate_R_-_The_apply_Family.md'     
    - RStudio:
        - Code & Plot Chunk Options: 'Code___Plot_Chunk_Options.md'
        - Working with the RStudio IDE: 'Working_with_RStudio_IDE.md'
    - Data Wrangling Snippets:
        - I/O snippets & Cleaning: 'IO_snippets___Cleaning.md'
        - Reading Data into R with readr: 'Reading_Data_into_R_with_readr.md'
        - Data Analysis in R, the data.table Way: 'Data_Analysis_in_R,_the_data.table_Way.md'
        - Data Manipulation in R with dplyr: 'Data_Manipulation_in_R_with_dplyr.md'
    - Plot Snippets:
        - Plot Snippets for Exploratory (and some Explanatory) Analyses: 'Plot_snippets_-_Basics.md'
        - Plot Snippets - ggplot2: 'Plot_snippets_-_ggplot2.md'
        - Plot Snippets - ggvis: 'Plot_snippets_-_ggvis.md'
        - Plot Snippets - Colours: 'Plot_snippets_-_Colours.md'
        - Improved codes: 'Improved_codes.md'
        - Formulas in R: 'Formulas_in_R.md'
    - Packages:
        - googleVis (embed HTML plots): 'googleVis.md'
        - gganimate: 'gganimate.md'
        - Fast-and-Frugal Decision Trees: 'Fast-and-Frugal_Decision_Trees_in_R_with_FFTrees.md'
    - Other Snippets: 
        - Tables: 'Tables.md'
        - Embedding HTML into HTML: 'embedding.md'
        - Embedding Rmd into Rmd: 'embedding2.md'
        - Frequentist vs. Bayesian: 'Frequentist_Bayesian.md'
        - Parallel computing in R: 'Parallel computing in R.md'
    - A Hands-on Introduction to Statistics with R:
        - Statistics with R, Course One, Introduction: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_One,_Introduction.md'
        - Statistics with R, Course Two, Student's t-test: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Two,_Student_s_T-test.md'
        - Statistics with R, Course Three, Analysis of Variance: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Three,_Analysis_of_Variance.md'
        - Statistics with R, Course Four, Repeated Measures ANOVA: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Four,_Repeated_Measures_Anova.md'
        - Statistics with R, Course Five, Correlation and Regression: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Five,_Correlation_and_Regression.md'
        - Statistics with R, Course Six, Multiple Regression: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Six,_Multiple_Regression.md'
        - Statistics with R, Course Seven, Moderation and Mediation: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Seven,_Moderation_and_Mediation.md'
        - Statistics with R, Notes: 'A_Hands-on_Introduction_to_Statistics_with_R,_Notes.md'
    - Big Data Analysis with Revolution R Enterprise: 'Big_Data_Analysis_with_Revolution_R_Enterprise.md'
    - Time Series in R, The Power of xts and zoo: 'Time+Series+in+R+The+Power+of+xts+and+zoo.md'

theme: readthedocs
# Other themes:
    # readthedocs
    # mkdocs

# Build PDF & ePub (only on Readthedocs)
#formats: 
#    - pdf

# Interlinks
# [link](to_other_page.md)
# [link](../relative/page.md)

# Math equations:
# extra JS (see below)
# extra Python (see below)
# new extension (see below)
# Required to load the MathJax javascript for the mdx_math.py
# https://github.com/mkdocs/mkdocs/issues/253

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True # for use of inline $..$
    - wikilinks # internal links with [[bracketed]]
    - smarty # additional characters
    - subscript
    - superscript
    - nl2br # need a new line to break
    - toc:
        title: CONTENT
        permalink: True
        baselevel: 3
    - footnotes
    
# Required to load the MathJax javascript for the mdx_math.py        
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']
